### ISSUE TITLE
implement adding/removing watcher

### ISSUE THREAD

**Issue by yeled** [mikepea/go-jira-ui#17]
This would be a *really* useful cli command, so I could filter out the ticket ID in a `mutt`  keybinf and add myself as a watcher.. without a browser window.

**Comment by mikepea** [comment]
This is possible via https://github.com/Netflix-Skunkworks/go-jira:

    jira watch ISSUE [-w WATCHER] [--remove]

`--remove` is only on master at the moment, awaiting release of 0.0.21
