### ISSUE TITLE
-e flag doesn't work

### ISSUE THREAD

**Issue by bobtfish** [mikepea/go-jira-ui#18]
./jira-ui --endoint=https://jira.yelpcorp.com

2016/01/27 09:48:39 Unknown option: --endoint=https://jira.yelpcorp.com
....
General Options:
  -e --endpoint=URI   URI to use for jira

**Comment by mikepea** [comment]
You spelt endpoint wrong :)

**Comment by bobtfish** [comment]
Duh-slexic this morning before coffee. Oops
