### ISSUE TITLE
Give option to disable default queries

### ISSUE THREAD

**Issue by poros** [mikepea/go-jira-ui#26]
I'd like my custom queries to be at the top of the page and I'm not gonna use the default ones now that I defined mine. Adding an option to disable default queries would be great :)

**Comment by mikepea** [comment]
Ack, i've thought about this and would like to get it added. Should be pretty straightforward.

**Comment by coryb** [comment]
what about just shifting the screen menu's around so that custom queries are first?
-Cory

**Comment by mikepea** [comment]
Closing this off, i think @coryb's update has made it unnecessary.
