### ISSUE TITLE
Improve date formatting

### ISSUE THREAD

**Issue by adulteratedjedi** [mikepea/go-jira-ui#31]
Instead of displaying dates like "2016-01-04T11:15:42.000+0000" it would be nice to be able to see them as 10 days ago/3 hours ago.

I am already working on a patch for this :+1:

**Comment by mikepea** [comment]
Hi Gavin,

Take a look at
https://github.com/Netflix-Skunkworks/go-jira/blob/master/util.go - you
should be able to accomplish what you want with the 'age' template function
(see fuzzyAge)



On Tue, Feb 23, 2016 at 5:28 PM, Gavin-John Noonan <notifications@github.com
